---
title: "Option A"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1 (37.5 points)

Take a Jane Austen book contained in the janeaustenr package, 

Make a plot of the most common words in the book, removing “stop words” of your choosing (words like “the”, “a”, etc.) or stopwords from a pre-defined source, like the stopwords package or tidytext::stop_words.

If you use any resources for helping you remove stopwords. name the source and link to it.

```{r}
#packages needed
library(janeaustenr)
library(ggplot2)
library(plotly)
library(hpackedbubble)
library(webshot)
library(tidyverse)
library(qdap)
```



```{r}

df <- janeaustenr::austen_books() %>% 
  nest(data = text) %>% 
  mutate(freq = map(data, 
                    ~ qdap::freq_terms(.x$text, 10,
                                       at.least = 5,                                        tm::stopwords("english"))))

df1 <- df %>%
  select(-data) %>% # assuming you don't need this column any longer
  unnest(freq)


bubplot <- hpackedbubble(df1$book, df1$WORD, df1$FREQ,
              title = "Common words in Jane Austens books",
              pointFormat = "<b>{point.name}:</b> {point.y} words<sub>",
              dataLabelsFilter = 100,
              packedbubbleMinSize = "50%",
              packedbubbleMaxSize = "300%",
              theme = "sunset",
              packedbubbleZMin = 0,
              packedbubbleZmax = 10000, split = 1,
              gravitational = 0.02,
              parentNodeLimit = 1,
              dragBetweenSeries = 0,
              width = "100%")

bubplot
```



